[package]
name = "rust_file_sync_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0"

[lib]
name = "rust_file_sync_tool"
path = "src/main.rs"
